<!doctype html>
 
<html lang="en">
<head>
  <title>Control LED Via Web | Arthtech Automation</title> 
</head>
 
<body>
<div style="text-align:center;width:80%; margin-left:auto; margin-right:auto;margin-top:150px;">
 <form method="post" action="./control.php">
 <input style="margin:auto;"  type="submit" id="on" name="on" value="Turn On" />
 <input style="margin:auto;" margin-right:auto;" type="submit" id="off" name="off" value="Turn Off" />
 </form>
</div>

</body>
 
</html>
